# Use the official Node.js image as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the React app
RUN npm run build

# Install a web server to serve the static files (e.g., serve)
RUN npm install -g serve

# Command to run the app
CMD ["serve", "-s", "build", "-l", "8080"]

# Expose the port the app runs on
EXPOSE 8080